### ISSUE TITLE
Restructuring the documentation of CoCli

### ISSUE THREAD

**Issue by hannestschofenig** [veraison/corim#102]
I am suggesting to make two changes to the documentation here:
https://github.com/veraison/corim/tree/main/cocli

1. Provide a high-level description upfront. A simplified version of this figure will do it: https://github.com/veraison/corim/tree/main/cocli#visual-synopsis-of-the-available-commands
2. In the command line examples use the data from the data directory. Currently, the command line examples use fictitious file names.

https://github.com/veraison/corim/pull/99 goes into this direction

**Comment by yogeshbdeshpande** [comment]
@hannestschofenig : To your point, I think the existing picture is a great summary that `displays` the overall capability of `cocli` tool!

Its just that it is far down below in the README.md

See a similar comment made by Ned Smith:
https://github.com/veraison/corim/issues/89

**Comment by yogeshbdeshpande** [comment]
@hannestschofenig Please check, if the https://github.com/veraison/corim/pull/99
now reflects what you were looking for?

I have addressed 1. and 2. reported in your original issue description.
