### ISSUE TITLE
ValueTriple has "measurements" should be "measurement" to match corim draft

### ISSUE THREAD

**Issue by deeglaze** [veraison/corim#123]
The reference-triple-record has 1 environment-map and 1 measurement-map. The ValueTriple's "measurements" collection does not follow that document structure, so I don't know how this produces a valid comid.

It would certainly seem to me that 1 environment could have multiple measurements of different names and value kinds the way this code allows for, but the draft doesn't allow for that. The mkey I thought was a way for multiplicity to be allowed, but also no.

**Comment by setrofim** [comment]
Looks like the code matches [rev00](https://www.ietf.org/archive/id/draft-birkholz-rats-corim-00.html) of the draft, and the triples structure was never brought into alignment with the later versions. We need to fix this.

**Comment by thomas-fossati** [comment]
Noting that this change would impact how PSA and CCA reference values are currently encoded.

**Comment by setrofim** [comment]
> Noting that this change would impact how PSA and CCA reference values are currently encoded.

Yup, this will have ripple effect on a lot of existing code. Fixing this is not going to be trivial...

**Comment by yogeshbdeshpande** [comment]
Yes, this was a known issue however, we had not scoped it fully so had put on hold for a while.

Has impact on PSA, CCA and also Parsec-CCA Scheme under Veraison

**Comment by setrofim** [comment]
@deeglaze this should be resolved by https://github.com/veraison/corim/pull/124
