### ISSUE TITLE
is key-id mandatory?

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/corim#14]
Track the outcome of the discussion around this issue: https://github.com/ietf-rats/ietf-corim-cddl/issues/131 and adjust code accordingly.  At the moment, the implementation does not treat key-id as mandatory.

**Comment by deeglaze** [comment]
It is mandatory https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#section-4.2.1
