### ISSUE TITLE
document the cocli template format

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/corim#24]
There has to be clear documentation around the template format used by:
* CoRIM
* Meta
* CoMID
* (Co)SWID

**Comment by ravjot07** [comment]
hey @thomas-fossati 
I wanted to check if this issue is still open and if any progress has been made. If the issue is unresolved, I would like to contribute to addressing it. Please let me know if I can start working on this and if there are any specific guidelines or priorities to consider.

**Comment by deeglaze** [comment]
@ravjot07 your contributions are welcome and greatly appreciated. This is not actively worked on.

**Comment by deeglaze** [comment]
Moved to cocli repo's issues https://github.com/veraison/cocli/issues/18
