### ISSUE TITLE
`cocli corim display` should be able to process unsigned CoRIMs too

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/corim#49]
If I try to use `cocli` to display an unsigned CoRIM:
```
> cocli corim display -f my-unsigned-corim.cbor -v
```
I get: _"Error: error decoding signed CoRIM from my-unsigned-corim.cbor: failed CBOR decoding for COSE-Sign1 signed CoRIM: cbor: cannot unmarshal map into Go value of type cbor.RawTag"_

**Comment by ravjot07** [comment]
Hey @thomas-fossati 
I've opened a pull request to enhance the corim display command by adding support for unsigned CoRIMs. I'd appreciate it if you could take a look at the PR and share your feedback.

Let me know if there’s anything I can clarify or adjust.

**Comment by deeglaze** [comment]
Closing since https://github.com/veraison/cocli/pull/14/files has been merged.
