### ISSUE TITLE
`cocli`'s default config file should be `${HOME}/.cocli`

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/corim#50]
Currently the default config file is `${HOME}/.cli`.  We should make it `${HOME}/.cocli`

**Comment by souravpy** [comment]
Can you kindly provide me with the location of the config file so that I can make suggested edits.

**Comment by setrofim** [comment]
the location for the default config file is `$XDG_CONFIG_HOME/cocli/config.yaml`, you can specify an alternate config file with `-c/--config`. (This is reported in the output of `cocli -h`)

**Comment by setrofim** [comment]
Resolved by 16eb57a4
