### ISSUE TITLE
Bug: cocli corim display

### ISSUE THREAD

**Issue by raghuncstate** [veraison/corim#69]
cocli corim display on a signed corim creates a json and prints "Meta:" and "CoRIM:" in https://github.com/veraison/corim/blob/main/cocli/cmd/corimDisplay.go#L88 and later.

This causes a problem when parsing the JSON file output through python or command line, and appears to be a non-conforming JSON.
Can you confirm this is a bug? and perhaps fix it?

Similarly cocli comid display also outputs the file name with >> at the top of the JSON file and makes it difficult to parse.

**Comment by yogeshbdeshpande** [comment]
@raghuncstate I hope you have fixed the issue by this date! If yes, could you please also introduce the fix on this repository.

Your contributions will be highly appreciated!

**Comment by deeglaze** [comment]
Moved this bug to the cocli repo https://github.com/veraison/cocli/issues/17
