### ISSUE TITLE
Visual Synopsis of the Available Commands diagram should appear sooner

### ISSUE THREAD

**Issue by nedmsmith** [veraison/corim#89]
The cocli readme has a synopsis diagram that should appear sooner (near the top) of the readme.

**Comment by yogeshbdeshpande** [comment]
@nedmsmith Please check the Merged PR: https://github.com/veraison/corim/pull/99

If ok, please close this issue!

**Comment by yogeshbdeshpande** [comment]
Closing as addressed by PR: #99
